export const NOTES_CONSTANTS = {
  TITLE_MIN_LENGTH: 1,
  TITLE_MAX_LENGTH: 100,
  CONTENT_MIN_LENGTH: 1,
  CONTENT_MAX_LENGTH: 2000,
  DEFAULT_MAX_NOTES_PER_USER: 10,
  PAGE_SIZE: 10,
  AUTOCOMPLETE_MAX_RESULTS: 25,
  MODAL_CUSTOM_ID_ADD: 'notes:modal:add',
  MODAL_CUSTOM_ID_EDIT_PREFIX: 'notes:modal:edit:',
  COMPONENT_LIST_PREFIX: 'notes:list:',
  COMPONENT_BTN_PREFIX: 'notes:btn:',
} as const;

